In [1]:
import pandas

In [2]:
ds = pandas.read_csv('salary.csv')

In [24]:
ds.head(5)

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [4]:
ds.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [5]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes


In [6]:
x = ds['YearsExperience'].values.reshape(30,1)

In [7]:
type(x)

numpy.ndarray

In [8]:
x.shape

(30, 1)

In [9]:
y = ds['Salary']

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
model = LinearRegression()

In [12]:
# algo 
model.fit(x , y)

LinearRegression()

In [13]:
model.coef_

array([9449.96232146])

In [14]:
# y = c +  wx
# 9449 * 1.1
model.predict([[ 1.1 ]] )

array([36187.15875227])

In [15]:
36187/39343 * 100

91.97824263528454

In [16]:
9449 * 1.1

10393.900000000001

In [17]:
c = model.intercept_

In [18]:
c

25792.20019866871

In [19]:
25792 + 9449 * 1.1

36185.9

In [20]:
import joblib

In [21]:
#save model
joblib.dump(model, "salary_model.pki")

['salary_model.pki']

In [25]:
#Predict again
model.predict([[ 1.3 ]] )

array([38077.15121656])